# SPDX-License-Identifier: MIT

option(KS_DHT_BUILD_TEST "Build ${PROJECT_NAME} unittest" ${PROJECT_IS_TOP_LEVEL})
option(KS_DHT_INSTALL "Install ${PROJECT_NAME}" ${PROJECT_IS_TOP_LEVEL})

if(NOT DEFINED KS_DHT_BUCKET_SIZE)
  set(KS_DHT_BUCKET_SIZE 20 CACHE STRING "Bucket size")
endif()

if(NOT DEFINED KS_DHT_PARALLEL_REQUEST_COUNT)
  set(KS_DHT_PARALLEL_REQUEST_COUNT 3 CACHE STRING "Parallel find peer request")
endif()

if(NOT DEFINED KS_DHT_EXCLUDING_RANGE_DEPTH)
  set(KS_DHT_EXCLUDING_RANGE_DEPTH 3 CACHE STRING "Excluding range depth")
endif()

if(NOT DEFINED KS_DHT_REDUNDANT_SAVE_COUNT)
  set(KS_DHT_REDUNDANT_SAVE_COUNT 3 CACHE STRING "Redundant save count")
endif()

if(NOT DEFINED KS_DHT_REQUEST_TIMEOUT_MS)
  set(KS_DHT_REQUEST_TIMEOUT_MS 1000 CACHE STRING "Request timeout")
endif()
